### ISSUE TITLE
Intermittently missing all-product-headers.yaml

### ISSUE THREAD

**Issue by AndrewSB** [Instabug/Instabug-SP#14]
Hey! I intermittently run into this issue, and often cleaning/clearing derived data/resetting the package cache doesn't resolve it. It might have something to do with a newer version of the SDK?

I get the following error whenever I try to use the debugger 

```
(lldb) po anything
error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/Instabug-cvgnxykmqaptlvcvhwtspqfbequo/Build/Intermediates.noindex/ArchiveIntermediates/InstabugDynamic/IntermediateBuildFilesPath/Instabug.build/Release-iphoneos/InstabugDynamic.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/distiller/Library/Developer/Xcode/DerivedData/Instabug-cvgnxykmqaptlvcvhwtspqfbequo/Build/Intermediates.noindex/ArchiveIntermediates/InstabugDynamic/IntermediateBuildFilesPath/Instabug.build/Release-iphoneos/InstabugDynamic.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

Is this something that's being tracked? is there a fix/workaround?

**Comment by AndrewSB** [comment]
the file paths in there seem to be the included in from the machine that built the Instabug binary, I don't have a `/Users/distiller` on my machine

**Comment by AndrewSB** [comment]
seems related to https://github.com/facebook/facebook-ios-sdk/issues/1628, i'm going to try downgrading my version to workaround this for now

**Comment by husseinkishk** [comment]
@AndrewSB 
This is an issue in lldb, which happens sometimes when you are trying to integrate Instabug in a Swift-only project.

A workaround for this issue is to add Objective-C files and a bridging header to your project, like mentioned in this [StackOverflow post](https://stackoverflow.com/questions/54776459/whats-the-solution-for-error-couldnt-irgen-expression-no-additional-error/61824142#61824142).

Also please make sure you're using the latest version 10.7.3 before trying the workaround.
